name: Build and Test

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: Build and Test Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Project
        run: mvn clean install
